
author: CAMBIAZO
email: jccambiazo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I like bikes.

# social links

github_username: cambiazo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
